### ISSUE TITLE
The XeZrunner.UI project is missing.

### ISSUE THREAD

**Issue by jeuxjeux20** [XeZrunner/WebcamViewer#3]
The title says it all.

**Comment by XeZrunner** [comment]
Thank you for reporting this issue.
It has been acknowledged and will be fixed in a near-future commit.

**Comment by jeuxjeux20** [comment]
*The future is near*

**Comment by aepic999** [comment]
_The `foo`toore is near_

**Comment by jeuxjeux20** [comment]
```csharp
public class Foo : Toore {
public Foo() {}
}
```

**Comment by XeZrunner** [comment]
c744ab9ef957e0947efdf89834f3c5a05ed7d479 fixes this issue.
